version: "3"
services:
  php1:
    image: www-php:v1
    container_name: www-php1
    restart: always
    volumes:
        - ./www:/var/www/html

  php2:
    image: www-php:v1
    container_name: www-php2
    restart: always
    volumes:
        - ./www:/var/www/html

  nginx:
    depends_on:
      - php1
      - php2
    image: nginx:1.13.7
    container_name: www-nginx
    ports:
      - "80:80"
    restart: always
    volumes:
        - ./www:/data/www
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./nginx/www.conf:/etc/nginx/conf.d/default.conf
