name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd php-7.3-alpine && docker build . --file Dockerfile --tag php73-alpine:v1.0
